# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "master" ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

outputs:
  artifact_id:
    description: "The ID of the artifact that was uploaded."
    value: ${{ steps.upload-artifact.outputs.artifact-id }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Build the SPA in note-tree
        run: |
          cd note-tree
          npm ci
          npm run build
          cd ..
      
      - name: Archive the contents of note-tree
        run: |
          tar \
            --dereference --hard-dereference \
            --directory "./note-tree" \
            -cvf "$RUNNER_TEMP/github-pages-artifact.tar" \
            --exclude=.git \
            --exclude=.github \
            ./note-tree
            
      - name: Upload github pages artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ${{ runner.temp }}/github-pages-artifact.tar
          retention-days: 1
          if-no-files-found: error

  deploy:
    needs: build

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 